accounts/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path("password_change/", views.password_change,  name="password_change"),

    re_path(r'^(?P<username>[\w.@+-]+)/follow/\Z', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/\Z', views.user_unfollow, name='user_unfollow'),
]

instagram/urls.py
from django.urls import path, re_path
from . import views

app_name = 'instagram'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+\Z)', views.user_page, name='user_page'),
]

instagram/models.py
import re
from django.db import models
from django.conf import settings
from django.urls import reverse


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="instagram/post/%Y/%m")  # 필수 필드 지정
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           related_name='like_post_set', blank=True)

    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_instance_list = []
        for tag_name in tag_name_list:
            tag_instance, _ = Tag.objects.get_or_create(name=tag_name)
            tag_instance_list.append(tag_instance)
        return tag_instance_list

    def get_absolute_url(self):
        return reverse('instagram:post_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        ordering = ['-id']

instagram/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        widgets = {
            "caption": forms.Textarea
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            "message": forms.Textarea(attrs={"rows": 1})
        }

instagram/views.py
from datetime import timedelta
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import PostForm, CommentForm
from .models import Tag, Post


def index(request):
    timesince = timezone.now() - timedelta(days=3)
    post_list = Post.objects.all()\
        .filter(
        Q(author=request.user) |
        Q(author__in=request.user.following_set.all())
    )\
        .filter(created_at__gte=timesince)
    comment_form = CommentForm()

    suggested_user_list = get_user_model().objects.all() \
        .exclude(pk=request.user.pk) \
        .exclude(pk__in=request.user.following_set.all())  # 현재 following한 사람들은 보여주지 않음
    return render(request, "instagram/index.html", {
        'post_list': post_list,
        'suggested_user_list': suggested_user_list[:5],  # 추천친구 5명까지만
        'comment_form': comment_form,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장했습니다")
            return redirect(post)
    else:
        form = PostForm()
    return render(request, "instagram/post_form.html", context={
        'form': form,
    })


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    return render(request, "instagram/post_detail.html", {
        'post': post,
        'comment_form': comment_form,
    })


def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username)  # 해당 모델에 username 키워드 인자로 GET 요청
    post_list = Post.objects.filter(author=page_user)

    # 해당 유저가 follow 되어있는지 확인하는 변수
    if request.user.is_authenticated:
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    return render(request, "instagram/user_detail.html", {
        'page_user': page_user,
        'post_list': post_list,
        'is_follow': is_follow,
    })


@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # instance 생성
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect(comment.post)
    else:
        form = CommentForm()

    return render(request, 'instagram/comment_form.html', {
        'form': form,
    })

templates/instagram/_post_card.html
<div class="card">
    <div class="card-header">
        <img src="{{ post.author.profile_url }}" class="rounded-circle" style="width: 32px; height: 32px;"
             alt="유저 프로필 사진">
        <a href="{% url "instagram:user_page" post.author.username %}">
            {{ post.author.name }}
        </a>
    </div>
    <div class="card-body">
        <p><img src="{{ post.photo.url }}" style="width: 25%" alt="포스팅 사진"></p>
        {{ post.caption }} <br/><br/>

        {% for tag in post.tag_set.all %}
            <span class="badge text-bg-secondary">
                #{{ tag.name }}
            </span>
        {% endfor %}
    </div>
    <div class="card-footer">
        <div class="d-flex">
            <div class="p-1">
                {% load instagram_tags %}
                {% if post|is_like_user:user %}
                    <a href="{% url 'instagram:post_unlike' post.pk %}">
                        <i class="fa fa-heart" aria-hidden="true" style="color: #dc3545"></i>
                    </a>
                {% else %}
                    <a href="{% url 'instagram:post_like' post.pk %}">
                        <i class="fa fa-heart-o" aria-hidden="true" style="color: black"></i>
                    </a>
                {% endif %}
            </div>
            <div class="p-1">
                <a href="{% url 'instagram:comment_new' post.pk %}">
                    <i class="fa fa-comments" aria-hidden="true" style="color: black;"></i>
                </a>
            </div>
        </div>
        <div class="comment">
            {% load humanize %}
            {% for comment in post.comment_set.all %}
                <div>
                    <strong>{{ comment.author }}</strong>
                    {{ comment.message }}
                    <small class="text-muted ms-1">{{ comment.created_at|naturaltime }}</small>
                </div>
            {% endfor %}
            <form action="{% url 'instagram:comment_new' post.pk %}" method="post">
                {% csrf_token %}
                {{ comment_form }}
                <input type="submit" value="댓글 작성">
            </form>
        </div>
    </div>
</div>

templates/instagram/comment_form.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with submit_label="댓글 작성" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/instagram/index.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row mb-2">
            <div class="col-sm-12">
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">새 포스팅 쓰기</a>
            </div>
        </div>
        <div class="row">
            <!-- Timeline(포스팅 목록) 영역 -->
            <div class="col-sm-8">
                {% for post in post_list %}
                    <div class="mb-3">
                        {% include "instagram/_post_card.html" %}
                    </div>
                {% empty %}
                    보여줄 포스팅이 없습니다
                {% endfor %}
            </div>
            <!-- Sidebar 영역(스토리 및 친구추천) -->
            <div class="col-sm-4">
                {% include "instagram/timeline_sidebar.html" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/instagram/layout.html
{% extends "layout.html" %}

templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "instagram/_post_card.html" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/instagram/post_form.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with submit_label="글 작성" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/instagram/timeline_sidebar.html
<div class="d-flex p-2">
    <div class="me-3">
        <img src="{{ user.profile_url }}" class="rounded-circle" style="width: 48px; height: 48px;" alt="프로필 사진">
    </div>
    <div>
        <a href="{% url 'instagram:user_page' user.username %}" class="fw-bold">
            {{ user.username }}
        </a><br/>
        <p class="text-muted">{{ user.name }}</p>
    </div>
</div>

<div class="card mb-2">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card-body">
        친구들의 스토리 목록
    </div>
</div>

<div class="card">
    <div class="card-header text-muted">
        친구 추천
    </div>
    <div class="card-body">
        {% for suggested_user in suggested_user_list %}
            {% include "instagram/timeline_sidebar_user_follow.html" %}
        {% empty %}
            추천 친구가 없습니다
        {% endfor %}
    </div>
</div>

templates/instagram/timeline_sidebar_user_follow.html
<div class="d-flex mb-1">
    <div class="p-1">
        <img src="{{ suggested_user.profile_url }}" class="rounded-circle" style="height: 32px; width: 32px">
    </div>
    <div class="p-1">
        <a href="{% url 'instagram:user_page' suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ms-auto p-1">
        <a href="{% url "user_follow" suggested_user.username %}">Follow</a>
    </div>
</div>

templates/instagram/user_detail.html
{% extends "instagram/layout.html" %}
{% load thumbnail %}

{% block content %}
<div class="container">
    <div class="row pt-3 pb-3">
        <div class="col-sm-3" style="text-align: center">
            <img src="{{ page_user.profile_url }}" class="rounded-circle" style="width: 140px;" alt="프로필 이미지">
        </div>
        <div class="col-sm-9">
            <p>
                {{ page_user.username }}
                <a href="{% url 'profile_edit' %}" class="btn btn-group btn-sm">프로필 수정</a>

                {% if is_follow %}
                    <a href="{% url 'user_unfollow' page_user.username %}">Unfollow</a>
                {% else %}
                    <a href="{% url 'user_follow' page_user.username %}">Follow</a>
                {% endif %}

            </p>
            <p>{{ post_list.count }} posts, followers, following</p>
            {{ page_user.name }}
        </div>
    </div>
    <div class="row mt-3">
        {% for post in post_list %}
            <div class="col-sm-4">
                <img src="{% thumbnail post.photo 200x200 crop %}" alt="{{ post.caption }}" style="width: 100%">
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}